---
- hosts: all
  remote_user: root
  become: yes

  vars:
    ansible_python_interpreter: /usr/bin/python
    ansible_host: 10.135.155.154
    ansible_become_method: su
    ansible_connection: ssh
    ansible_ssh_user: alarm
    ansible_ssh_pass: alarm
    ansible_become_pass: root

  tasks:
    - name: Init key
      ansible.builtin.command: pacman-key --init

    - name: Populate key
      ansible.builtin.command: pacman-key --populate archlinuxarm

