---
ansible_host: 10.135.155.163
boot_partition_suffix: '2'
root_partition_suffix: '3'
boottype: bios
# This file is for use by update-ip-addr.sh
wired_interface: eno1
use_wireless: yes
wireless_interface: wlo1
